server:
  port: 8080
spring:
  application:
    name: ms-company-service

  data:
    mongodb:
      uri: "${MONGO_URI:mongodb+srv://mario:mario@cluster0.t4gtdev.mongodb.net/}"
      database: company
  redis:
    host: 0.0.0.0
    port: 6379

